# Generated by Django 5.2.10 on 2026-02-16 05:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon identifier e.g. lightning, target, fire', max_length=50)),
                ('criteria', models.JSONField(help_text='JSON criteria for auto-awarding, e.g. {"type":"modules_per_day","threshold":3}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=True)),
                ('notify_course_updates', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=20)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_style_override', models.CharField(blank=True, choices=[('mindmap', 'Mind Map'), ('videos', 'Videos'), ('summary', 'Summary Notes'), ('books', 'Books'), ('reels', 'Short Reels')], default='', help_text='Per-course learning style override', max_length=20)),
                ('diagnosed_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Level determined by diagnostic assessment', max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=10)),
                ('overall_progress', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage 0.00–100.00', max_digits=5)),
                ('total_study_time_minutes', models.PositiveIntegerField(default=0)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_style', models.CharField(choices=[('mindmap', 'Mind Map'), ('videos', 'Videos'), ('summary', 'Summary Notes'), ('books', 'Books'), ('reels', 'Short Reels')], default='summary', max_length=20)),
                ('depth_preference', models.CharField(choices=[('surface', 'Surface'), ('deep', 'Deep')], default='deep', max_length=10)),
                ('pace_preference', models.CharField(choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('fast', 'Fast')], default='moderate', max_length=10)),
                ('quiz_preference', models.BooleanField(default=True, help_text='Whether user prefers frequent quizzes')),
                ('attention_span_minutes', models.PositiveIntegerField(default=25, help_text='Estimated attention span in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_profiles',
            },
        ),
        migrations.CreateModel(
            name='LearningRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, help_text='Increments when roadmap is refined after quiz')),
                ('roadmap_data', models.JSONField(help_text='Full roadmap JSON: {"topics": [{"topic_name": "", "level": ""}]}')),
                ('generated_by_model', models.CharField(default='llama3:8b-instruct-q4_K_M', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='api.enrollment')),
            ],
            options={
                'db_table': 'learning_roadmaps',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(help_text='Position in the course sequence')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60)),
                ('is_generated', models.BooleanField(default=False, help_text='True if AI-generated from roadmap')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.course')),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, default='', help_text='AI-generated lesson content (Markdown/HTML)')),
                ('order', models.PositiveIntegerField()),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.module')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=15)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progresses', to='api.enrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='api.module')),
            ],
            options={
                'db_table': 'module_progress',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('diagnostic', 'Diagnostic Assessment'), ('topic_quiz', 'Topic Quiz'), ('final_quiz', 'Final Quiz')], max_length=15)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('difficult', 'Difficult')], max_length=15)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text='List of option strings, e.g. ["A","B","C","D"]')),
                ('correct_answer_index', models.PositiveSmallIntegerField(help_text='0-based index into options list')),
                ('explanation', models.TextField(blank=True, default='', help_text='Explanation of correct answer')),
                ('is_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.course')),
                ('module', models.ForeignKey(blank=True, help_text='Null for diagnostic questions, set for topic/final quizzes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.module')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('diagnostic', 'Diagnostic Assessment'), ('topic_quiz', 'Topic Quiz'), ('final_quiz', 'Final Quiz')], max_length=15)),
                ('score_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('weak_areas', models.JSONField(blank=True, default=list, help_text='List of weak area strings from AI evaluation')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='api.enrollment')),
                ('module', models.ForeignKey(blank=True, help_text='Set for topic quizzes, null for diagnostic', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='api.module')),
            ],
            options={
                'db_table': 'quiz_attempts',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option_index', models.SmallIntegerField(blank=True, help_text='Null if user skipped', null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('response_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='api.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.quizattempt')),
            ],
            options={
                'db_table': 'quiz_answers',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('notes', 'Summary Notes'), ('pdf', 'PDF Document'), ('ppt', 'Presentation'), ('mindmap', 'Mind Map'), ('video_script', 'Video Script (JSON)'), ('video', 'Video (MP4)'), ('audio', 'Audio/Podcast (MP3)'), ('image', 'Image (PNG)'), ('reel', 'Short Reel')], max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('content_text', models.TextField(blank=True, default='', help_text='Text content (for notes, scripts, mindmap data)')),
                ('content_json', models.JSONField(blank=True, help_text='Structured content (video scripts with scenes, mindmap nodes)', null=True)),
                ('file', models.FileField(blank=True, help_text='For binary files: PDFs, PPTs, videos, audio, images', null=True, upload_to='resources/%Y/%m/')),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='For audio/video resources', null=True)),
                ('is_generated', models.BooleanField(default=False)),
                ('generation_model', models.CharField(blank=True, default='', help_text='e.g. llama3:8b-instruct-q4_K_M, stable-diffusion-v1-5', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.lesson')),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievements',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('module_completed', 'Module Completed'), ('course_started', 'Course Started'), ('assessment_passed', 'Assessment Passed'), ('quiz_completed', 'Quiz Completed'), ('achievement_earned', 'Achievement Earned'), ('course_completed', 'Course Completed')], max_length=25)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, help_text='Extra context e.g. {"score": 85, "course_id": 1}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'status'], name='enrollments_user_id_b5f69f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='learningroadmap',
            index=models.Index(fields=['enrollment', 'is_active'], name='learning_ro_enrollm_1ea467_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('enrollment', 'module')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['course', 'question_type'], name='questions_course__0b1be0_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['module', 'question_type'], name='questions_module__1b61ac_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['enrollment', 'attempt_type'], name='quiz_attemp_enrollm_a7aca1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['lesson', 'resource_type'], name='resources_lesson__27467c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
