# Generated by Django 5.2.10 on 2026-02-16 07:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('progress_message', models.TextField(blank=True, default='')),
                ('script_data', models.JSONField(blank=True, help_text='Generated script JSON from Ollama', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Final generated video file', null=True, upload_to='videos/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, help_text='Optional link to a lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_tasks', to='api.lesson')),
            ],
            options={
                'db_table': 'video_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
