# Generated by Django 5.2.10 on 2026-02-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_videotask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('data_science', 'Data Science'), ('ai_ml', 'AI & Machine Learning'), ('mobile_dev', 'Mobile Development'), ('cloud', 'Cloud Computing'), ('design', 'Design'), ('devops', 'DevOps'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=60, help_text='Estimated duration in minutes'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_popular',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, default='', help_text='URL to course thumbnail image'),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['category', 'is_popular'], name='courses_categor_fa7dda_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='courses_created_c00611_idx'),
        ),
    ]
