# Generated by Django 5.2.10 on 2026-02-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_course_options_course_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_data', models.JSONField(help_text='Full personalized syllabus JSON with modules and topics')),
                ('generated_by_model', models.CharField(default='phi3:mini', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='api.enrollment')),
            ],
            options={
                'verbose_name_plural': 'Personalized syllabi',
                'db_table': 'personalized_syllabi',
            },
        ),
    ]
