# Generated by Django 5.2.10 on 2026-02-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_personalizedsyllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprofile',
            name='podcast_auto_generate',
            field=models.BooleanField(default=False, help_text='Automatically generate podcasts for new topics'),
        ),
        migrations.AddField(
            model_name='learningprofile',
            name='podcast_enabled',
            field=models.BooleanField(default=True, help_text='Enable audio podcast generation for topics'),
        ),
    ]
