# Generated by Django 5.2.10 on 2026-02-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_learningprofile_podcast_auto_generate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_sub_topic',
            field=models.BooleanField(default=True, help_text='True if this is a learnable sub-topic, False if broad topic category'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of specific learning objectives for this sub-topic'),
        ),
        migrations.AddField(
            model_name='course',
            name='parent_topic_name',
            field=models.CharField(blank=True, default='', help_text='Name of the broad topic this sub-topic belongs to (e.g., "AI & Machine Learning")', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list, help_text='List of prerequisite sub-topic names or IDs'),
        ),
    ]
