# Generated by Django 5.2.10 on 2026-02-19 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_course_is_sub_topic_course_learning_objectives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlanningTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_title', models.CharField(help_text='Title of the course/topic to plan', max_length=255)),
                ('course_description', models.TextField(help_text='Description of what should be covered')),
                ('category', models.CharField(choices=[('web_dev', 'Web Development'), ('data_science', 'Data Science'), ('ai_ml', 'AI & Machine Learning'), ('mobile_dev', 'Mobile Development'), ('cloud', 'Cloud Computing'), ('design', 'Design'), ('devops', 'DevOps'), ('cybersecurity', 'Cybersecurity'), ('blockchain', 'Blockchain'), ('other', 'Other')], default='other', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_duration', models.PositiveIntegerField(default=60, help_text='Estimated duration in minutes')),
                ('thumbnail', models.URLField(blank=True, default='', help_text='URL to course thumbnail')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('progress_message', models.TextField(blank=True, default='')),
                ('result_data', models.JSONField(blank=True, help_text='Complete course plan result from LLM (is_broad, courses, etc.)', null=True)),
                ('created_courses', models.JSONField(blank=True, help_text='IDs of courses created from this plan', null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course_planning_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
