# Generated by Django 5.2.10 on 2026-02-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_created_by_to_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='assessment_questions_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of questions in the pre-knowledge assessment (determined by LLM based on complexity)', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='custom_study_method',
            field=models.TextField(blank=True, default='', help_text='Custom study method description when study_method_preference is "custom"'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='study_method_preference',
            field=models.CharField(choices=[('real_world', 'Real-world Examples'), ('theory_depth', 'Theory Depth'), ('project_based', 'Project-Based'), ('custom', 'Custom')], default='real_world', help_text='How the student prefers to learn (affects syllabus generation)', max_length=20),
        ),
    ]
