# Generated by Django 5.2.10 on 2026-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_study_method_to_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='ai_system_prompt',
            field=models.TextField(blank=True, default='', help_text="AI-generated system prompt personalized to the user's learning style for this enrollment. Used as the LLM system instruction for notes and audio generation (not quiz)."),
        ),
    ]
