# Generated by Django 5.2.10 on 2026-03-02 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_ai_system_prompt_to_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], help_text='Whether this is a user message or assistant response', max_length=10)),
                ('content', models.TextField(help_text='The actual message content')),
                ('topic_name', models.CharField(blank=True, default='', help_text='Optional: Which topic was being discussed', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(help_text='The enrollment this chat message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='api.enrollment')),
            ],
            options={
                'db_table': 'chat_history',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['enrollment', 'created_at'], name='chat_histor_enrollm_27b2a1_idx')],
            },
        ),
    ]
