# Generated by Django 5.2.10 on 2026-03-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_lessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Set for topic quizzes to identify specific topic/lesson', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='api.lesson'),
        ),
    ]
