# Generated by Django 5.2.10 on 2026-03-06 00:00

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_quizattempt_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('starter_code', models.TextField(blank=True, default='')),
                ('reference_solution', models.TextField(blank=True, default='')),
                ('language', models.CharField(choices=[('python', 'Python')], default='python', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('intermediate', 'Intermediate'), ('difficult', 'Difficult')], default='intermediate', max_length=15)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('hints', models.JSONField(blank=True, default=list)),
                ('is_generated', models.BooleanField(default=False)),
                ('generation_model', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to='api.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to='api.lesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coding_problems', to='api.module')),
            ],
            options={
                'db_table': 'coding_problems',
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('python', 'Python')], default='python', max_length=20)),
                ('source_code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('score_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('passed_tests', models.PositiveSmallIntegerField(default=0)),
                ('total_tests', models.PositiveSmallIntegerField(default=0)),
                ('feedback', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='api.enrollment')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.codingproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='api.user')),
            ],
            options={
                'db_table': 'code_submissions',
            },
        ),
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('is_hidden', models.BooleanField(default=False)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api.codingproblem')),
            ],
            options={
                'db_table': 'coding_test_cases',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodeExecutionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('progress_message', models.TextField(blank=True, default='')),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='execution_task', to='api.codesubmission')),
            ],
            options={
                'db_table': 'code_execution_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('diagnostic', 'Diagnostic Assessment'), ('topic_quiz', 'Topic Quiz'), ('final_quiz', 'Final Quiz'), ('code_problem', 'Code Problem')], max_length=15),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('notes', 'Summary Notes'), ('pdf', 'PDF Document'), ('ppt', 'Presentation'), ('mindmap', 'Mind Map'), ('video_script', 'Video Script (JSON)'), ('video', 'Video (MP4)'), ('audio', 'Audio/Podcast (MP3)'), ('image', 'Image (PNG)'), ('reel', 'Short Reel'), ('code_exercise', 'Code Exercise')], max_length=15),
        ),
        migrations.AddIndex(
            model_name='codingproblem',
            index=models.Index(fields=['course', 'language'], name='coding_prob_course__a9ec5c_idx'),
        ),
        migrations.AddIndex(
            model_name='codingproblem',
            index=models.Index(fields=['lesson', '-created_at'], name='coding_prob_lesson__7beb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['user', '-submitted_at'], name='code_submis_user_id_77e903_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['problem', '-submitted_at'], name='code_submis_problem_028ac5_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['enrollment', '-submitted_at'], name='code_submis_enrollm_27cc9b_idx'),
        ),
        migrations.AddIndex(
            model_name='codingtestcase',
            index=models.Index(fields=['problem', 'is_hidden'], name='coding_test_problem_375fc3_idx'),
        ),
    ]
